---
title: Ithaca Reggae Fest
timezone: America/New_York
collections:
  artists:
    title: Artists
    output: true
    options:
      hidden: false
  grids:
    title: Grids
    output: false
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
